parameters:
    fnz.institution.form.type.institution_address.class: InstitutionBundle\Form\Type\InstitutionAddressType
    fnz.institution.form.type.fnz.institution.class:         InstitutionBundle\Form\Type\InstitutionType
    fnz.institution.form.type.account.class:             InstitutionBundle\Form\Type\AccountType


services:
    fnz.institution.form.type.institution:
        class: '%fnz.institution.form.type.fnz.institution.class%'
        tags:
            - { name: form.type, alias: institution_institution_type }

    # Custom Address form type to Institution
    fnz.institution.form.type.institution_address:
        class: '%fnz.institution.form.type.institution_address.class%'
        arguments:
            - '@oro_address.form.listener.address'
            - '@oro_address.form.listener.address_identifier'
        tags:
             - { name: form.type, alias: institution_institution_address_type }

    fnz.institution.form.type.account:
        class: '%fnz.institution.form.type.account.class%'
        tags:
            - { name: form.type, alias: institution_account_type }

    fnz.institution.form.type.institution_select:
            class: 'InstitutionBundle\Form\Type\InstitutionSelectType'
            arguments:
                - "@translator"
            tags:
                - { name: form.type, alias: institution_institution_select_type }

    fnz.institution.form.type.account_select:
            class: 'InstitutionBundle\Form\Type\AccountSelectType'
            arguments:
                - "@translator"
            tags:
                - { name: form.type, alias: institution_account_select_type }
