parameters:
    institution.entity.institution.class: InstitutionBundle\Entity\Institution

services:

    institution.institution_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        public: true
        arguments:
            - InstitutionBundle\Entity\Institution
            - "@doctrine.orm.entity_manager"
