parameters:
    fnz.institution.entity.institution.class: InstitutionBundle\Entity\Institution
    fnz.institution.entity.account.class:     InstitutionBundle\Entity\Account

services:

    fnz.institution.institution_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        public: true
        arguments:
            - InstitutionBundle\Entity\Institution
            - "@doctrine.orm.entity_manager"

    fnz.account.account_manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        public: true
        arguments:
            - InstitutionBundle\Entity\Account
            - "@doctrine.orm.entity_manager"

    fnz.institution.institution_search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - InstitutionBundle\Entity\Institution
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: institutions, acl_resource: fnz.institution.institution_view }
