parameters:
  fnz.accountancy.form.type.book.class:              AccountancyBundle\Form\Type\BookType
  fnz.accountancy.form.type.record.class:            AccountancyBundle\Form\Type\RecordType
  fnz.accountancy.form.type.category_select.class:   AccountancyBundle\Form\Type\CategorySelectType
  fnz.accountancy.form.type.category.class:          AccountancyBundle\Form\Type\CategoryType

services:

  fnz.accountancy.form.type.book:
    class: '%fnz.accountancy.form.type.book.class%'
    tags:
      - { name: form.type, alias: fnz_accountancy_book_type }

  fnz.accountancy.form.type.add_new_record:
    class: '%fnz.accountancy.form.type.record.class%'
    tags:
      - { name: form.type, alias: fnz_accountancy_record_type }

  fnz.accountancy.form.type.category_select:
    class: '%fnz.accountancy.form.type.category_select.class%'
    tags:
      - { name: form.type, alias: fnz_accountancy_category_select_type }

  fnz.accountancy.form.type.category:
    class: '%fnz.accountancy.form.type.category.class%'
    tags:
      - { name: form.type, alias: fnz_accountancy_category_type }
