parameters:
  fnz.accountancy.manager.book.class:                       AccountancyBundle\Manager\BookManager

services:
  fnz.accountancy.book.manager.book_manager:
    public: true
    class: '%fnz.accountancy.manager.book.class%'
    arguments:
      - '@doctrine'

#  fnz.accountancy.category.manager.category_manager:
#    public: true
#    class: '%fnz.accountancy.manager.book.class%'
#    arguments:
#      - '@doctrine'