parameters:
  fnz.accountancy.entity.book.class:                       AccountancyBundle\Entity\Book
  fnz.accountancy.entity.category.class:                   AccountancyBundle\Entity\Category
  fnz.accountancy.entity.record.class:                     AccountancyBundle\Entity\Record
  fnz.accountancy.entity.tag.class:                        AccountancyBundle\Entity\Tag
  fnz.accountancy.entity.beneficiary.class:                AccountancyBundle\Entity\Beneficiary
  fnz.accountancy.entity.schedule_transaction.class:       AccountancyBundle\Entity\ScheduledTransaction

services:

  fnz.accountancy.category_search_handler:
    parent: oro_form.autocomplete.search_handler
    public: yes
    arguments:
      - '%fnz.accountancy.entity.category.class%'
      - ["name"]
    tags:
      - { name: oro_form.autocomplete.search_handler, alias: fnz_categories, acl_resource: category_view }