datagrids:
    institutions-grid:
        extended_entity_name: '%fnz.institution.entity.institution.class%'
        source:
            acl_resource: fnz.institution.institution_view
            type: orm
            query:
                select:
                    - i
                from:
                    - { table: InstitutionBundle:Institution, alias: i }
        columns:
            name:
                label: institution.name.label
            branchNumber:
                label: institution.branch_number.label
            iban:
                label: institution.iban.label
            bic:
                label: institution.bic.label
        properties:
            id: ~
            view_link:
              type: url
              route: fnz.institution.institution_view
              params:
                - id
            update_link:
                type: url
                route: fnz.institution.institution_update
                params:
                    - id
            delete_link:
                type: url
                route: institution_api_delete_institution
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: i.name
                branchNumber:
                    data_name: i.branchNumber
                iban:
                    data_name: i.iban
                bic:
                    data_name: i.bic
            default:
                model: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: i.name
                branchNumber:
                    type: string
                    data_name: i.branchNumber
                iban:
                    type: string
                    data_name: i.iban
                bic:
                    type: string
                    data_name: i.bic
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  fnz.institution.institution_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  fnz.institution.institution_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  fnz.institution.institution_delete

    institution-form-select-grid:
        extends: institutions-grid

    accounts-grid:
        extended_entity_name: '%fnz.institution.entity.account.class%'
        source:
            acl_resource: fnz.account.account_view
            type: orm
            query:
                select:
                    - a
                from:
                    - { table: InstitutionBundle:Account, alias: a }
        columns:
            name:
                label: account.name.label
            number:
                label: account.number.label
            currency:
                label: account.currency.label
            openingBalance:
                label: account.opening_balance.label
            minimumBalanceToNotify:
                label: account.minimum_balance_to_notify.label
                type: money_value
            openingDate:
                label: account.opening_date.label
                frontend_type: date
            favorite:
                label: account.favorite.label
                frontend_type: boolean
            accountingType:
                label: account.accounting_type.label
            type:
                label: account.type.label
        properties:
            id: ~
            view_link:
              type: url
              route: fnz.account.account_view
              params:
                - id
            update_link:
                type: url
                route: fnz.account.account_update
                params:
                    - id
            delete_link:
                type: url
                route: account_api_delete_account
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: a.name
                number:
                    data_name: a.number
                currency:
                    data_name: a.currency
                    type: currency
                openingBalance:
                    data_name: a.openingBalance
                minimumBalanceToNotify:
                    data_name: a.minimumBalanceToNotify
                openingDate:
                    data_name: a.openingDate
                favorite:
                    data_name: a.favorite
                accountingType:
                    data_name: a.accountingType
                type:
                    data_name: a.type
            default:
                name: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: a.name
                number:
                    type: string
                    data_name: a.number
                currency:
                    type: string
                    data_name: currency
                openingBalance:
                    type: currency
                    data_name: openingBalance
                minimumBalanceToNotify:
                    type: currency
                    data_name: a.minimumBalanceToNotify
                openingDate:
                    type: date
                    data_name: a.openingDate
                favorite:
                    type: boolean
                    data_name: a.favorite
                accountingType:
                    type: string
                    data_name: a.accountingType
                type:
                    type: string
                    data_name: a.type
        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          eye-open
                acl_resource:  fnz.account.account_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  fnz.account.account_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  fnz.account.account_delete

    institution-view-accounts-grid:
        extends: accounts-grid
        source:
            query:
                join:
                    left:
                        institution:
                            join: a.institution
                            alias: i
                where:
                    and:
                        - i.id = :institution_id
            bind_parameters:
                -
                    name:  institution_id
                    default: null

        action_configuration:
            delete: false

    account-form-select-grid:
        extends: accounts-grid
