navigation:
    menu_config:

        items:
            institution_tab:
                label: 'institution.menu.institution_tab.label'
                uri: '#'
                position: 300
                extras:
                    icon: fa-handshake-o
            institution_list:
                label: 'institution.entity_plural_label'
                route: 'institution.institution_index'
                position: 200
                extras:
                    routes: ['/^institution/']
                    description: 'institution.entity_plural_label'

        tree:
            application_menu:
                children:
                    institution_tab:
                        children:
                            institution_list: ~


    titles:
        institution.institution_index: ~
        institution.institution_view:  '%entityName% - oro.ui.view'
        institution.institution_update: '%entityName% - oro.ui.edit'
        institution.institution_create: 'oro.ui.create_entity'
