imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

doctrine:
    dbal:
        logging:            true

monolog:
    handlers:
        detailed_logs:
            type:           service
            id:             oro_logger.monolog.detailed_logs.handler
            handler:        nested
            channels:       ["!consumer"]
        nested:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug
            channels:       ["!consumer"]

        fingers_crossed:
            type:           fingers_crossed
            action_level:   critical
            handler:        deduplicated
            buffer_size:    1000
        deduplicated:
            type:           deduplication
            handler:        swift
            buffer_size:    1000
        swift:
            type:           swift_mailer
            email_prototype:
                id:         oro_logger.message_factory
                method:     createMessage
            mailer:         swiftmailer.mailer.default
            level:          debug
            formatter:      monolog.formatter.html

        # only records with level 'notice' and higher should pass to `consumer_%kernel.environment%.log` file
        filter_consumer:
            type:           filter
            min_level:      notice
            handler:        consumer
            channels:      ["consumer"]
        # collect all log records to buffer and write them to 'consumer_%kernel.environment%.log' file on CLI command error
        message_queue.consumer.console_error:
            type:           service
            id:             oro_message_queue.log.handler.console_error
            handler:        consumer
            level:          debug
        # write all records from 'consumer' consumer channel to 'consumer_%kernel.environment%.log'
        consumer:
            type:          rotating_file
            path:          "%kernel.logs_dir%/consumer_%kernel.environment%.log"
            level:         debug
            max_files:     7
            channels:      ["consumer"]

oro_require_js:
    build_logger: false
