label: FNZ Theme
logo: bundles/fnz/themes/fnz/images/logo.svg
icon: bundles/fnz/themes/fnz/images/favicon.ico
styles:
    css:
        inputs:
            - bundles/oroui/themes/oro/css/style.css
        output: css/themes/oro/oro.css
