accountancy_bundle_book:
  resource: "@AccountancyBundle/Controller/BookController.php"
  type: annotation
  prefix: /book

accountancy_bundle_category:
  resource: "@AccountancyBundle/Controller/CategoryController.php"
  type: annotation
  prefix: /category

accountancy_bundle_record:
  resource: "@AccountancyBundle/Controller/RecordController.php"
  type: annotation
  prefix: /record

#accountancy_bundle_account:
#  resource: "@InstitutionBundle/Controller/AccountController.php"
#  type: annotation
#  prefix: /account

book_api_book:
  resource: "@AccountancyBundle/Controller/Api/Rest/BookController.php"
  type: rest
  prefix: api/rest/{version}/
  requirements:
    version: latest|v1
    _format: json
  defaults:
    version: latest

category_api_category:
  resource: "@AccountancyBundle/Controller/Api/Rest/CategoryController.php"
  type: rest
  prefix: api/rest/{version}/
  requirements:
    version: latest|v1
    _format: json
  defaults:
    version: latest

record_api_record:
  resource: "@AccountancyBundle/Controller/Api/Rest/RecordController.php"
  type: rest
  prefix: api/rest/{version}/
  requirements:
    version: latest|v1
    _format: json
  defaults:
    version: latest